const STALLIONS = [
  {
    name: "A Sparkling Vintage",
    slug: "a-sparkling-vintage",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-a-sparkling-vintage/w=400",
    tier: "premium",
    discipline: ["reining","reined cow horse"],
    stud_fee: 6000,
    lifetime_earnings: 54516,
    offspring_earnings: 4654000,
    performance_summary: "NRHA 4 Million Dollar Sire · Sire of 2 NRHA Triple Crown Champions",
    enrollments: ["NRHA Sire & Dam","NRBC","IRHBA","AQHA Incentive Fund"],
    bloodlines: ["Shining Spark","Peppy San Badger","Genuine Doc","Vintage Badger"],
    traits: ["stop","athleticism","handle","softness","scope"],
    sire: "Shining Spark",
    dam: "Vintage Badger by Peppy San Badger",
    description: "The only sire in NRHA history to produce two Triple Crown Champions. A Sparkling Vintage stands retired at Silver Spurs Arizona, available via ICSI only. Sire of A Vintage Smoke ($600K), Not Ruf At All ($456K), and Platinum Vintage ($390K).",
    breeding_note: "ICSI only. Pay breeding fee only when you have a live foal."
  },
  {
    name: "Big Chex To Cash",
    slug: "big-chex-to-cash",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-big-chex-to-cash/w=400",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 750,
    lifetime_earnings: 220826,
    offspring_earnings: 1370000,
    performance_summary: "2005 NRHA Open Futurity Reserve Champion · NRHA Million Dollar Sire",
    enrollments: ["NRHA Sire & Dam","NRBC"],
    bloodlines: ["Nu Chex To Cash","Colonel Freckles","One Gun","Bueno Chex"],
    traits: ["stop","athleticism","speed","softness","handle"],
    sire: "Nu Chex To Cash",
    dam: "Snip O Gun by One Gun",
    description: "2002 Palomino AQHA/APHA double-registered stallion. 2005 NRHA Open Futurity Reserve Champion. NRHA Million Dollar Sire with offspring earnings exceeding $1.37M. Sire of 473 AQHA foals, 163 money-earners.",
    breeding_note: "ICSI only. Deceased — breeding via frozen ICSI semen only."
  },
  {
    name: "Boomernic",
    slug: "boomernic",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-boomernic/w=400",
    tier: "premium",
    discipline: ["reining","reined cow horse"],
    stud_fee: 3500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Elite reining and reined cow horse sire",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Reminic","Colonel Freckles","Nu Chex To Cash"],
    traits: ["cow sense","athleticism","handle","rate","stop"],
    sire: "Reminic",
    dam: "Colonel Freckles mare",
    description: "The Greats tier stallion combining elite Reminic and Colonel Freckles bloodlines for reining and cow horse production.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Conquistador Whiz",
    slug: "conquistador-whiz",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-conquistador-whiz/w=400",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 4000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Topsail Whiz son · Elite reining sire · The Greats",
    enrollments: ["NRHA Sire & Dam","NRBC"],
    bloodlines: ["Topsail Whiz","Colonel Freckles","Smart Chic Olena"],
    traits: ["stop","speed","athleticism","power","scope"],
    sire: "Topsail Whiz",
    dam: "Colonel Freckles mare",
    description: "The Greats tier Whiz/Gunner cross. Topsail Whiz son combining speed, stop, and scope for elite reining production.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Spooks Gotta Gun",
    slug: "spooks-gotta-gun",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-spooks-gotta-gun/w=400",
    tier: "premium",
    discipline: ["reining","ranch"],
    stud_fee: 6500,
    lifetime_earnings: 81637,
    offspring_earnings: 4101569,
    performance_summary: "NRHA Triple Crown Champion Sire · $4M+ Offspring · Ranch $202K+",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Grays Starlight","Peppy San Badger","One Gun","Katie Gun"],
    traits: ["stop","athleticism","cow sense","versatility","speed","scope"],
    sire: "Grays Starlight",
    dam: "Katie Gun by One Gun",
    description: "2002 Bay Overo AQHA/APHA stallion. NRHA Triple Crown Champion Sire. First foal crop produced the 2010 NRHA Futurity Open Champion. Also sires Ranch ($202K+), Working Cow ($108K+), and Barrel ($22K+) horses.",
    breeding_note: "Available frozen semen and ICSI. Pay balance after confirmed pregnancy."
  },
  {
    name: "Trashadeous",
    slug: "trashadeous",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-trashadeous/w=400",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 4000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "The Greats · Top reining sire · Topsail Whiz son",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Topsail Whiz","Smart Chic Olena","Nu Chex To Cash"],
    traits: ["stop","speed","power","scope","athleticism"],
    sire: "Topsail Whiz",
    dam: "Smart Chic Olena mare",
    description: "The Greats tier. Combines Topsail Whiz power and Smart Chic Olena handle for elite reining production.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Wimpys Little Step",
    slug: "wimpys-little-step",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-wimpys-little-step/w=400",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 6500,
    lifetime_earnings: 185757,
    offspring_earnings: 15165000,
    performance_summary: "NRHA Hall of Fame · 2002 NRHA Futurity Open Champion · $15M+ Sire",
    enrollments: ["NRHA Sire & Dam","NRBC","IRHBA","AQHA Incentive Fund"],
    bloodlines: ["Nu Chex To Cash","Colonel Freckles","Wimpy Leo","Leolita Step"],
    traits: ["stop","athleticism","handle","softness","scope","speed","power"],
    sire: "Nu Chex To Cash",
    dam: "Leolita Step",
    description: "1999 Palomino stallion. 2011 NRHA Hall of Fame inductee. Won the 2002 NRHA Futurity with the highest composite score in NRHA history. The $15M sire — 50% of his 1,988 foals are money earners with average earnings over $11,000.",
    breeding_note: "ICSI only. Retired at Silver Spurs Oklahoma. Pay balance only when live foal on ground."
  },
  {
    name: "HF Mobster",
    slug: "hf-mobster",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-hf-mobster/w=400",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2500,
    lifetime_earnings: 123626,
    offspring_earnings: 1717000,
    performance_summary: "2013 NRHA Derby Champion · WEG Team Member · NRHA Million Dollar Sire",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Colonels Smoking Gun","Colonel Freckles","Hollywood Dun It","Dun Its Black Gold"],
    traits: ["stop","athleticism","handle","scope","power","speed"],
    sire: "Colonels Smoking Gun (Gunner)",
    dam: "Dun Its Black Gold",
    description: "2008 Buckskin AQHA/APHA stallion. 2013 NRHA Open Derby Champion. 2014 World Equestrian Games Team Member. NRHA Million Dollar Sire with offspring earnings $1.7M+. Fee reduced to $2,500 for 2026.",
    breeding_note: "Standing at Silver Spurs Arizona. Pay balance after confirmed pregnancy."
  },
  {
    name: "Shiners Voodoo Dr",
    slug: "shiners-voodoo-dr",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-shiners-voodoo-dr/w=400",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 6000,
    lifetime_earnings: 87098,
    offspring_earnings: 8065000,
    performance_summary: "NRHA $7M Sire · NRCHA $1M Sire · Total offspring $8M+",
    enrollments: ["NRHA Sire & Dam","NRBC","NRCHA Sire & Dam"],
    bloodlines: ["Shining Spark","Smart Chic Olena","Genuine Doc","Voodoo Chic"],
    traits: ["stop","athleticism","cow sense","softness","scope","handle"],
    sire: "Shining Spark",
    dam: "Voodoo Chic by Smart Chic Olena",
    description: "2007 AQHA Palomino stallion. Dual-discipline powerhouse — NRHA $7 Million Sire and NRCHA $1 Million Sire. Total offspring earnings $8M+. Produces elite reining and reined cow horse horses.",
    breeding_note: "Standing at Silver Spurs Arizona. Pay balance after confirmed pregnancy."
  },
  {
    name: "Tinker With Guns",
    slug: "tinker-with-guns",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-tinker-with-guns/w=400",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2000,
    lifetime_earnings: 346366,
    offspring_earnings: 1521000,
    performance_summary: "2011 NRHA Open Derby Champion · NRHA Million Dollar Sire",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Colonels Smoking Gun","Colonel Freckles","Reminic","Tinker Nic"],
    traits: ["stop","speed","athleticism","power","scope","handle"],
    sire: "Colonels Smoking Gun (Gunner)",
    dam: "Tinker Nic by Reminic",
    description: "2006 Sorrel AQHA/APHA stallion. 2011 NRHA Open Derby Champion. 2012 NRBC Open Derby Reserve Champion. NRHA Million Dollar Sire. Offspring earnings $1.52M+. Standing in Oklahoma.",
    breeding_note: "Standing at Silver Spurs Oklahoma. Pay balance after confirmed pregnancy."
  },
  {
    name: "Wimpyneedsacocktail",
    slug: "wimpyneedsacocktail",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-wimpyneedsacocktail/w=400",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 3500,
    lifetime_earnings: 281804,
    offspring_earnings: 0,
    performance_summary: "NRBC Open Derby Champion · AQHA Reserve World Champion · Son of Wimpys Little Step",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Nu Chex To Cash","Colonel Freckles","Wimpy Leo","Wimpys Little Step"],
    traits: ["stop","athleticism","scope","speed","handle","softness"],
    sire: "Wimpys Little Step",
    dam: "Nu Chex To Cash mare",
    description: "Son of Wimpys Little Step. NRBC Open Derby Champion. AQHA Reserve World Champion Senior and Junior Reining Horse. LTE $281,804.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Platinum Vintage",
    slug: "platinum-vintage",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-platinum-vintage/w=400",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2500,
    lifetime_earnings: 390828,
    offspring_earnings: 0,
    performance_summary: "2015 NRHA Open Derby Champion · Son of A Sparkling Vintage",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Shining Spark","Peppy San Badger","A Sparkling Vintage"],
    traits: ["stop","athleticism","scope","softness","handle"],
    sire: "A Sparkling Vintage",
    dam: "Shining Spark mare",
    description: "2015 NRHA Open Derby Champion. Son of A Sparkling Vintage. LTE $390,828. Silver Spurs homebred — now standing as a sire.",
    breeding_note: "Standing at Silver Spurs Arizona."
  },
  {
    name: "Xtra New Pal Voodoo",
    slug: "xtra-new-pal-voodoo",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-xtra-new-pal-voodoo/w=400",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 3000,
    lifetime_earnings: 109894,
    offspring_earnings: 0,
    performance_summary: "NRHA/NRCHA earner $109K · Son of Shiners Voodoo Dr",
    enrollments: ["NRHA Sire & Dam","NRCHA Sire & Dam"],
    bloodlines: ["Shining Spark","Nu Chex To Cash","Smart Chic Olena","Wimpys Little Step"],
    traits: ["stop","cow sense","athleticism","softness","scope"],
    sire: "Shiners Voodoo Dr",
    dam: "Wimpys New Pal by Wimpys Little Step",
    description: "Son of Shiners Voodoo Dr out of a Wimpys Little Step mare. Dual NRHA and NRCHA earner — $109,894 including $28,000 SSBF.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Ifwhizswereguns",
    slug: "ifwhizswereguns",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-ifwhizswereguns/w=400",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 3000,
    lifetime_earnings: 118578,
    offspring_earnings: 0,
    performance_summary: "High Roller Open Classic Futurity Champion · NRBC Top Ten",
    enrollments: ["NRHA Sire & Dam","NRBC"],
    bloodlines: ["Grays Starlight","Topsail Whiz","Colonel Freckles","Spooks Gotta Gun"],
    traits: ["stop","speed","athleticism","scope","power"],
    sire: "Spooks Gotta Gun",
    dam: "Topsail Whiz mare",
    description: "Son of Spooks Gotta Gun out of a Topsail Whiz mare. High Roller Reining Open Classic Futurity Champion. NRBC Reining Derby Open Top Ten. LTE $118,578.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Custom Cash Advance",
    slug: "custom-cash-advance",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-custom-cash-advance/w=400",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 3000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Nu Chex To Cash son · Gunner cross · Reining specialist",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Nu Chex To Cash","Colonels Smoking Gun","Colonel Freckles"],
    traits: ["stop","athleticism","handle","scope","softness"],
    sire: "Nu Chex To Cash",
    dam: "Colonels Smoking Gun mare",
    description: "Nu Chex To Cash / Colonels Smoking Gun cross. Reining specialist combining two of the most influential sire lines in the industry.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Smart Shiners Spook",
    slug: "smart-shiners-spook",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-smart-shiners-spook/w=400",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 3000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Dual discipline · Spooks Gotta Gun x Shining Spark cross",
    enrollments: ["NRHA Sire & Dam","NRCHA Sire & Dam"],
    bloodlines: ["Grays Starlight","Shining Spark","Smart Chic Olena"],
    traits: ["stop","athleticism","cow sense","handle","scope"],
    sire: "Spooks Gotta Gun",
    dam: "Shining Spark mare",
    description: "Spooks Gotta Gun x Shining Spark dual-discipline cross. Bred for both reining and reined cow horse production.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Nic It In The Bud",
    slug: "nic-it-in-the-bud",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-nic-it-in-the-bud/w=400",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 3000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Reminic son · Reining and cow horse specialist",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Reminic","Smart Chic Olena","Colonel Freckles"],
    traits: ["cow sense","athleticism","stop","handle","rate"],
    sire: "Reminic",
    dam: "Smart Chic Olena mare",
    description: "Reminic son with cow horse aptitude from Smart Chic Olena dam line. Produces horses with natural cattle instinct and solid reining foundation.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Einsteins Revolution",
    slug: "einsteins-revolution",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-einsteins-revolution/w=400",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Topsail Whiz / Smart Chic Olena cross",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Topsail Whiz","Smart Chic Olena","Nu Chex To Cash"],
    traits: ["stop","athleticism","softness","scope"],
    sire: "Topsail Whiz",
    dam: "Smart Chic Olena mare",
    description: "Topsail Whiz son out of a Smart Chic Olena mare. Combines Whiz athleticism with Olena softness for a trainable, scopey reining prospect.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Mister Montana Nic",
    slug: "mister-montana-nic",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-mister-montana-nic/w=400",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 2500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Reminic son · Reining and cow horse",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Reminic","Colonel Freckles","Nu Chex To Cash"],
    traits: ["cow sense","athleticism","handle","rate","stop"],
    sire: "Reminic",
    dam: "Colonel Freckles mare",
    description: "Reminic x Colonel Freckles cross. Strong cow horse aptitude with reining foundation. Versatile producer for dual-discipline programs.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Chic Dreamin",
    slug: "chic-dreamin",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-chic-dreamin/w=400",
    tier: "value",
    discipline: ["reining","reined cow horse"],
    stud_fee: 0,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "FREE breeding 2026 · Smart Chic Olena son",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Smart Chic Olena","Grays Starlight","Colonel Freckles"],
    traits: ["athleticism","softness","cow sense","handle"],
    sire: "Smart Chic Olena",
    dam: "Grays Starlight mare",
    description: "Free breeding for the entire 2026 season. Smart Chic Olena son with natural cow sense and handle. Outstanding opportunity to access elite bloodlines at zero stud fee.",
    breeding_note: "FREE breeding 2026. Available cooled or ICSI."
  },
  {
    name: "Electric Wind",
    slug: "electric-wind",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-electric-wind/w=400",
    tier: "value",
    discipline: ["reining","ranch"],
    stud_fee: 0,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "FREE breeding 2026 · Colonels Smoking Gun son",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Colonels Smoking Gun","Grays Starlight","Smart Chic Olena"],
    traits: ["speed","athleticism","versatility","stop"],
    sire: "Colonels Smoking Gun",
    dam: "Grays Starlight mare",
    description: "Free breeding for the entire 2026 season. Gunner son with Grays Starlight athleticism. Versatile producer for reining and ranch horse programs.",
    breeding_note: "FREE breeding 2026. Available cooled or ICSI."
  },
  {
    name: "Pale Face Dunnit",
    slug: "pale-face-dunnit",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-pale-face-dunnit/w=400",
    tier: "value",
    discipline: ["reining","ranch"],
    stud_fee: 2000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Reduced fee 2026 · Hollywood Dun It son",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Hollywood Dun It","Smart Chic Olena","Colonel Freckles"],
    traits: ["athleticism","versatility","softness","stop","handle"],
    sire: "Hollywood Dun It",
    dam: "Smart Chic Olena mare",
    description: "Hollywood Dun It son with Smart Chic Olena dam. Fee reduced from $3,750 to $2,000 for the entire 2026 breeding season. Versatile reining and ranch horse producer.",
    breeding_note: "Reduced to $2,000 for all of 2026."
  },
  {
    name: "Catatomic",
    slug: "catatomic",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-catatomic/w=400",
    tier: "value",
    discipline: ["reining","reined cow horse"],
    stud_fee: 1500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Junior stallion · High Brow Cat / Gunner cross",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["High Brow Cat","Colonels Smoking Gun","Smart Chic Olena"],
    traits: ["cow sense","athleticism","quick feet","stop"],
    sire: "Colonels Smoking Gun",
    dam: "High Brow Cat mare",
    description: "Junior stallion. High Brow Cat cutting bloodlines crossed into Colonels Smoking Gun reining. Natural cow sense meets reining athleticism.",
    breeding_note: "Junior stallion. Standing at Silver Spurs Equine."
  },
  {
    name: "My Customized Whiz",
    slug: "my-customized-whiz",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-my-customized-whiz/w=400",
    tier: "value",
    discipline: ["reining"],
    stud_fee: 1500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Junior stallion · Topsail Whiz / Gunner / Smart Chic Olena",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Topsail Whiz","Smart Chic Olena","Colonels Smoking Gun"],
    traits: ["stop","speed","power","athleticism","scope"],
    sire: "Topsail Whiz",
    dam: "Smart Chic Olena / Gunner mare",
    description: "Junior stallion combining three elite reining sire lines: Topsail Whiz, Smart Chic Olena, and Colonels Smoking Gun. Outstanding reining bloodline combination at junior pricing.",
    breeding_note: "Junior stallion. Standing at Silver Spurs Equine."
  },
  {
    name: "Docs Soula",
    slug: "docs-soula",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-docs-soula/w=400",
    tier: "value",
    discipline: ["reined cow horse","cutting"],
    stud_fee: 1500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Junior stallion · Doc Bar / Smart Chic Olena · Cow horse and cutting",
    enrollments: ["NRCHA Sire & Dam"],
    bloodlines: ["Doc Bar","Smart Chic Olena","Colonel Freckles"],
    traits: ["cow sense","athleticism","rate","turn","quick feet"],
    sire: "Doc Bar",
    dam: "Smart Chic Olena mare",
    description: "Junior stallion with deep cow horse and cutting lineage. Doc Bar foundation crossed with Smart Chic Olena handle. Ideal for cow horse and cutting programs seeking proven cattle bloodlines.",
    breeding_note: "Junior stallion. Standing at Silver Spurs Equine."
  },
];
