const STALLIONS = [
  {
    name: "A Sparkling Vintage",
    slug: "a-sparkling-vintage",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/a-sparkling-vintage",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-a-sparkling-vintage/public",
    tier: "premium",
    discipline: ["reining","reined cow horse"],
    stud_fee: 6000,
    lifetime_earnings: 54516,
    offspring_earnings: 4654000,
    performance_summary: "NRHA 4 Million Dollar Sire · Sire of 2 NRHA Triple Crown Champions",
    enrollments: ["NRHA Sire & Dam","NRBC","IRHBA","AQHA Incentive Fund"],
    bloodlines: ["Shining Spark","Peppy San Badger","Genuine Doc","Vintage Badger"],
    traits: ["stop","athleticism","handle","softness","scope"],
    sire: "Shining Spark",
    dam: "Vintage Badger by Peppy San Badger",
    description: "The only sire in NRHA history to produce two Triple Crown Champions. A Sparkling Vintage is an NRHA 4 Million Dollar Sire with offspring earnings exceeding $4.6M. Available via ICSI only. Sire of A Vintage Smoke ($600K) and Not Ruf At All ($456K).",
    breeding_note: "ICSI breeding only; normal $10,000 fee reduced to absorb ICSI costs. Breeding fee due only on a live foal on the ground."
  },
  {
    name: "Big Chex To Cash",
    slug: "big-chex-to-cash",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/big-chex-to-cash-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-big-chex-to-cash/public",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 750,
    lifetime_earnings: 220826,
    offspring_earnings: 1370000,
    performance_summary: "2005 NRHA Open Futurity Reserve Champion · NRHA Million Dollar Sire",
    enrollments: ["NRHA Sire & Dam","NRBC"],
    bloodlines: ["Nu Chex To Cash","Colonel Freckles","One Gun","Bueno Chex"],
    traits: ["stop","athleticism","speed","softness","handle"],
    sire: "Nu Chex To Cash",
    dam: "Snip O Gun by One Gun",
    description: "NRHA Million Dollar Sire and 2005 Open Futurity Reserve Champion. Big Chex To Cash has produced 163 money-earners from 473 AQHA foals with offspring earnings over $1.37M. Available via ICSI only using frozen semen from this deceased champion.",
    breeding_note: "ICSI breeding. Million Dollar Challenge price, 50% off the standard fee. Pay $200, balance after a live foal."
  },
  {
    name: "Boomernic",
    slug: "boomernic",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/boomernic-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-boomernic/public",
    tier: "premium",
    discipline: ["reining","reined cow horse"],
    stud_fee: 1000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Elite reining and reined cow horse sire",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Reminic","Colonel Freckles","Nu Chex To Cash"],
    traits: ["cow sense","athleticism","handle","rate","stop"],
    sire: "Reminic",
    dam: "Colonel Freckles mare",
    description: "Elite reining and reined cow horse sire combining Reminic athleticism with Colonel Freckles cow sense. Boomernic stands in The Greats tier and consistently produces horses with natural cattle instinct, solid stops, and the trainability demanded in today's competition pen.",
    breeding_note: "Frozen semen only. Million Dollar Challenge season price, reduced from $5,000. Pay $500 now, balance on confirmed pregnancy."
  },
  {
    name: "Conquistador Whiz",
    slug: "conquistador-whiz",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/conquistador-whiz-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-conquistador-whiz/public",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 1000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Topsail Whiz son · Elite reining sire · The Greats",
    enrollments: ["NRHA Sire & Dam","NRBC"],
    bloodlines: ["Topsail Whiz","Colonel Freckles","Smart Chic Olena"],
    traits: ["stop","speed","athleticism","power","scope"],
    sire: "Topsail Whiz",
    dam: "Colonel Freckles mare",
    description: "A Topsail Whiz son standing in The Greats tier. Conquistador Whiz crosses Whiz speed and scope with Colonel Freckles handle, producing powerful reining prospects with scopey stops and the athleticism to compete at the highest levels of the NRHA.",
    breeding_note: "Million Dollar Challenge season price, reduced from $3,000. Includes frozen semen fee. Pay $500 now, balance on confirmed pregnancy."
  },
  {
    name: "Spooks Gotta Gun",
    slug: "spooks-gotta-gun",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/spooks-gotta-gun",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-spooks-gotta-gun/public",
    tier: "premium",
    discipline: ["reining","ranch"],
    stud_fee: 6500,
    lifetime_earnings: 81637,
    offspring_earnings: 4101569,
    performance_summary: "NRHA Triple Crown Champion Sire · $4M+ Offspring · Ranch $202K+",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Grays Starlight","Peppy San Badger","One Gun","Katie Gun"],
    traits: ["stop","athleticism","cow sense","versatility","speed","scope"],
    sire: "Grays Starlight",
    dam: "Katie Gun by One Gun",
    description: "NRHA Triple Crown Champion Sire with offspring earnings over $4.1M. Spooks Gotta Gun's first foal crop produced the 2010 NRHA Futurity Champion. Also sires Ranch ($202K+) and Working Cow ($108K+) horses. Available via frozen semen and ICSI.",
    breeding_note: "Fee shown is the ICSI breeding fee; frozen semen is $7,000. ICSI fee $1,000 now, balance due after a live foal is born."
  },
  {
    name: "Trashadeous",
    slug: "trashadeous",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/trashadeous",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-trashadeous/public",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 1000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "The Greats · Top reining sire · Topsail Whiz son",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Topsail Whiz","Smart Chic Olena","Nu Chex To Cash"],
    traits: ["stop","speed","power","scope","athleticism"],
    sire: "Topsail Whiz",
    dam: "Smart Chic Olena mare",
    description: "The Greats tier reining sire combining Topsail Whiz power with Smart Chic Olena handle. Trashadeous produces horses with elite stop mechanics, natural scope, and the speed demanded in modern reining competition. A proven cross for high-level reining programs.",
    breeding_note: "Million Dollar Challenge season price, reduced from $3,000. Includes frozen semen fee. Pay $500 now, balance on confirmed pregnancy."
  },
  {
    name: "Wimpys Little Step",
    slug: "wimpys-little-step",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/wimpys-little-step",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-wimpys-little-step/public",
    tier: "premium",
    discipline: ["reining"],
    stud_fee: 6500,
    lifetime_earnings: 185757,
    offspring_earnings: 15165000,
    performance_summary: "NRHA Hall of Fame · 2002 NRHA Futurity Open Champion · $15M+ Sire",
    enrollments: ["NRHA Sire & Dam","NRBC","IRHBA","AQHA Incentive Fund"],
    bloodlines: ["Nu Chex To Cash","Colonel Freckles","Wimpy Leo","Leolita Step"],
    traits: ["stop","athleticism","handle","softness","scope","speed","power"],
    sire: "Nu Chex To Cash",
    dam: "Leolita Step",
    description: "NRHA Hall of Fame. 2002 NRHA Futurity Open Champion with the highest composite score in history. Wimpys Little Step is a $15M sire — 50% of his 1,988 foals are money earners. Available via ICSI only at Silver Spurs Oklahoma.",
    breeding_note: "ICSI breeding only; normal $10,000 fee reduced to absorb ICSI costs. ICSI fee $1,000 now, balance on a live foal on the ground."
  },
  {
    name: "HF Mobster",
    slug: "hf-mobster",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/hf-mobster",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-hf-mobster/public",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2500,
    lifetime_earnings: 123626,
    offspring_earnings: 1717000,
    performance_summary: "2013 NRHA Derby Champion · WEG Team Member · NRHA Million Dollar Sire",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Colonels Smoking Gun","Colonel Freckles","Hollywood Dun It","Dun Its Black Gold"],
    traits: ["stop","athleticism","handle","scope","power","speed"],
    sire: "Colonels Smoking Gun (Gunner)",
    dam: "Dun Its Black Gold",
    description: "2013 NRHA Open Derby Champion and 2014 World Equestrian Games Team member. HF Mobster is an NRHA Million Dollar Sire with offspring earnings over $1.7M. Fee reduced to $2,500 for 2026. Standing at Silver Spurs Arizona.",
    breeding_note: "Million Dollar Challenge season price. Booking fee $750, balance on confirmed pregnancy."
  },
  {
    name: "Shiners Voodoo Dr",
    slug: "shiners-voodoo-dr",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/shiners-voodoo-dr",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-shiners-voodoo-dr/public",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 6000,
    lifetime_earnings: 87098,
    offspring_earnings: 8065000,
    performance_summary: "NRHA $7M Sire · NRCHA $1M Sire · Total offspring $8M+",
    enrollments: ["NRHA Sire & Dam","NRBC","NRCHA Sire & Dam"],
    bloodlines: ["Shining Spark","Smart Chic Olena","Genuine Doc","Voodoo Chic"],
    traits: ["stop","athleticism","cow sense","softness","scope","handle"],
    sire: "Shining Spark",
    dam: "Voodoo Chic by Smart Chic Olena",
    description: "NRHA $7 Million Sire and NRCHA $1 Million Sire with combined offspring earnings exceeding $8M. Shiners Voodoo Dr is the premier dual-discipline producer in the Silver Spurs program, consistently delivering elite reining and reined cow horse offspring.",
    breeding_note: "Standing at Silver Spurs Arizona. Pay balance after confirmed pregnancy."
  },
  {
    name: "Tinker With Guns",
    slug: "tinker-with-guns",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/tinker-with-guns",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-tinker-with-guns/public",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2000,
    lifetime_earnings: 346366,
    offspring_earnings: 1521000,
    performance_summary: "2011 NRHA Open Derby Champion · NRHA Million Dollar Sire",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Colonels Smoking Gun","Colonel Freckles","Reminic","Tinker Nic"],
    traits: ["stop","speed","athleticism","power","scope","handle"],
    sire: "Colonels Smoking Gun (Gunner)",
    dam: "Tinker Nic by Reminic",
    description: "2011 NRHA Open Derby Champion and NRHA Million Dollar Sire. Tinker With Guns has produced offspring earnings of $1.52M including top performer Tinker With Dreams at $432K. Outstanding value at $2,000 standing in Oklahoma.",
    breeding_note: "Standing at Silver Spurs Oklahoma. Pay balance after confirmed pregnancy."
  },
  {
    name: "Wimpyneedsacocktail",
    slug: "wimpyneedsacocktail",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/wimpyneedsacocktail",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-wimpyneedsacocktail/public",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2000,
    lifetime_earnings: 281804,
    offspring_earnings: 0,
    performance_summary: "NRBC Open Derby Champion · AQHA Reserve World Champion · Son of Wimpys Little Step",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Nu Chex To Cash","Colonel Freckles","Wimpy Leo","Wimpys Little Step"],
    traits: ["stop","athleticism","scope","speed","handle","softness"],
    sire: "Wimpys Little Step",
    dam: "Nu Chex To Cash mare",
    description: "Son of Wimpys Little Step and NRBC Open Derby Champion. Wimpyneedsacocktail earned $281,804 LTE including AQHA Reserve World Champion Senior and Junior Reining titles. Carries the Wimpy handle and athleticism into a new generation of reining horses.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Platinum Vintage",
    slug: "platinum-vintage",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/platinum-vintage",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-platinum-vintage/public",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2500,
    lifetime_earnings: 390828,
    offspring_earnings: 0,
    performance_summary: "2015 NRHA Open Derby Champion · Son of A Sparkling Vintage",
    enrollments: ["NRHA Sire & Dam","NRBC","AQHA Incentive Fund"],
    bloodlines: ["Shining Spark","Peppy San Badger","A Sparkling Vintage"],
    traits: ["stop","athleticism","scope","softness","handle"],
    sire: "A Sparkling Vintage",
    dam: "Shining Spark mare",
    description: "2015 NRHA Open Derby Champion and Silver Spurs homebred son of A Sparkling Vintage. Platinum Vintage earned $390,828 LTE and now passes elite Shining Spark and Peppy San Badger bloodlines to the next generation at an accessible $2,500 fee.",
    breeding_note: "Standing at Silver Spurs Arizona."
  },
  {
    name: "Xtra New Pal Voodoo",
    slug: "xtra-new-pal-voodoo",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/xtranewpalvoodoo",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-xtra-new-pal-voodoo/public",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 1250,
    lifetime_earnings: 109894,
    offspring_earnings: 0,
    performance_summary: "NRHA/NRCHA earner $109K · Son of Shiners Voodoo Dr",
    enrollments: ["NRHA Sire & Dam","NRCHA Sire & Dam"],
    bloodlines: ["Shining Spark","Nu Chex To Cash","Smart Chic Olena","Wimpys Little Step"],
    traits: ["stop","cow sense","athleticism","softness","scope"],
    sire: "Shiners Voodoo Dr",
    dam: "Wimpys New Pal by Wimpys Little Step",
    description: "Son of Shiners Voodoo Dr out of a Wimpys Little Step mare. Xtra New Pal Voodoo is a dual NRHA and NRCHA earner with $109,894 in total earnings including $28,000 SSBF. A proven dual-discipline sire at $3,000.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Ifwhizswereguns",
    slug: "ifwhizswereguns",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/ifwhizswereguns",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-ifwhizswereguns/public",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 1500,
    lifetime_earnings: 118578,
    offspring_earnings: 0,
    performance_summary: "High Roller Open Classic Futurity Champion · NRBC Top Ten",
    enrollments: ["NRHA Sire & Dam","NRBC"],
    bloodlines: ["Grays Starlight","Topsail Whiz","Colonel Freckles","Spooks Gotta Gun"],
    traits: ["stop","speed","athleticism","scope","power"],
    sire: "Spooks Gotta Gun",
    dam: "Topsail Whiz mare",
    description: "Son of Spooks Gotta Gun out of a Topsail Whiz mare. Ifwhizswereguns earned $118,578 LTE including the High Roller Reining Open Classic Futurity Championship and NRBC Top Ten finish. Combines Gun athleticism with Whiz precision.",
    breeding_note: "Standing at Silver Spurs Equine."
  },
  {
    name: "Custom Cash Advance",
    slug: "custom-cash-advance",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/custom-cash-advance-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-custom-cash-advance/public",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 750,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Nu Chex To Cash son · Gunner cross · Reining specialist",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Nu Chex To Cash","Colonels Smoking Gun","Colonel Freckles"],
    traits: ["stop","athleticism","handle","scope","softness"],
    sire: "Nu Chex To Cash",
    dam: "Colonels Smoking Gun mare",
    description: "Nu Chex To Cash crossed on Colonels Smoking Gun — two of the most influential reining sire lines in history. Custom Cash Advance combines inherited handle, stop, and scope to produce horses bred for the demands of high-level reining competition.",
    breeding_note: "Million Dollar Challenge season price, reduced from $1,500. Booking fee $250, balance due on a foal on the ground."
  },
  {
    name: "Smart Shiners Spook",
    slug: "smart-shiners-spook",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/smart-shiners-spook",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-smart-shiners-spook/public",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Dual discipline · Spooks Gotta Gun x Shining Spark cross",
    enrollments: ["NRHA Sire & Dam","NRCHA Sire & Dam"],
    bloodlines: ["Grays Starlight","Shining Spark","Smart Chic Olena"],
    traits: ["stop","athleticism","cow sense","handle","scope"],
    sire: "Spooks Gotta Gun",
    dam: "Shining Spark mare",
    description: "Spooks Gotta Gun crossed on Shining Spark — a proven dual-discipline combination. Smart Shiners Spook is enrolled in both NRHA and NRCHA sire programs, producing horses with natural cow sense, solid stops, and the scope needed across both disciplines.",
    breeding_note: "ICSI breeding. Million Dollar Challenge season price, reduced from $1,000. Pay $200 ICSI fee now, balance on a live foal."
  },
  {
    name: "Nic It In The Bud",
    slug: "nic-it-in-the-bud",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/nic-it-in-the-bud-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-nic-it-in-the-bud/public",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 3500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Reminic son · Reining and cow horse specialist",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Reminic","Smart Chic Olena","Colonel Freckles"],
    traits: ["cow sense","athleticism","stop","handle","rate"],
    sire: "Reminic",
    dam: "Smart Chic Olena mare",
    description: "Reminic son out of a Smart Chic Olena mare. Nic It In The Bud combines Reminic's proven cow horse athleticism with Smart Chic Olena handle, producing horses with natural cattle instinct and a solid reining foundation at $3,000.",
    breeding_note: "Frozen semen fee $3,500, includes the frozen semen fee. Booking fee $1,000, balance on confirmed pregnancy."
  },
  {
    name: "Einsteins Revolution",
    slug: "einsteins-revolution",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/einsteins-revolution",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-einsteins-revolution/public",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 3000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Topsail Whiz / Smart Chic Olena cross",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Topsail Whiz","Smart Chic Olena","Nu Chex To Cash"],
    traits: ["stop","athleticism","softness","scope"],
    sire: "Topsail Whiz",
    dam: "Smart Chic Olena mare",
    description: "Topsail Whiz son out of a Smart Chic Olena mare. Einsteins Revolution pairs Whiz athleticism and scope with Olena softness and trainability, producing a balanced reining prospect. An efficient cross for breeders seeking competitive horses at a value fee.",
    breeding_note: "Deceased — frozen and ICSI breeding only. Frozen semen fee $3,000, includes the frozen semen fee. Booking fee $1,000, balance on confirmed pregnancy."
  },
  {
    name: "Mister Montana Nic",
    slug: "mister-montana-nic",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/mister-montana-nic-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-mister-montana-nic/public",
    tier: "mid",
    discipline: ["reining","reined cow horse"],
    stud_fee: 500,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Reminic son · Reining and cow horse",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Reminic","Colonel Freckles","Nu Chex To Cash"],
    traits: ["cow sense","athleticism","handle","rate","stop"],
    sire: "Reminic",
    dam: "Colonel Freckles mare",
    description: "Reminic crossed on Colonel Freckles — a proven reining and cow horse combination. Mister Montana Nic produces horses with strong cattle instinct, reliable rate, and the athleticism demanded across both disciplines. A versatile sire for dual-discipline breeding programs.",
    breeding_note: "Booking fee $200, balance due on confirmed pregnancy."
  },
  {
    name: "SG Frozen Enterprize",
    slug: "sg-frozen-enterprize",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/sg-frozen-enterprize",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 5500,
    lifetime_earnings: 274083,
    offspring_earnings: 5478000,
    performance_summary: "2015 NRBC Level 4 Open Champion \u00b7 NRHA 5 Million Dollar Sire \u00b7 8 championship titles USA & Europe",
    enrollments: ["Silver Spurs Breeders Futurity", "Xtra Silver Spurs Breeders Futurity", "NRHA enrolled"],
    bloodlines: ["Frozen Sailor", "SJ Enterprise", "RS Rose SJ"],
    traits: [],
    sire: "Frozen Sailor",
    dam: "RS Rose SJ by SJ Enterprise",
    description: "Known as \"Iceman.\" 2009 red dun stallion, LTE $274,083, with 8 championship titles across the United States and Europe including the 2015 NRBC Level 4 Open Championship and the 2014 AQHA World Championship in Junior Reining. NRHA 5 Million Dollar Sire with offspring earnings over $5.47M.",
    breeding_note: "Standing at Silver Spurs Equine, Purcell OK. Booking fee $1,000, balance due on confirmed pregnancy."
  },
  {
    name: "Chic Dreamin",
    slug: "chic-dreamin",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/chicdreamin",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-chic-dreamin/public",
    tier: "value",
    discipline: ["reining","reined cow horse"],
    stud_fee: 2000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Smart Chic Olena son · Reining and cow horse · $2,000 fee 2026",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Smart Chic Olena","Grays Starlight","Colonel Freckles"],
    traits: ["athleticism","softness","cow sense","handle"],
    sire: "Smart Chic Olena",
    dam: "Grays Starlight mare",
    description: "Smart Chic Olena son with Grays Starlight athleticism. Chic Dreamin is a Smart Chic Olena son with natural cow sense and handle for reining and cow horse production at $2,000 for 2026.",
    breeding_note: "Million Dollar Challenge season price. Booking fee $500, balance on confirmed pregnancy."
  },
  {
    name: "Electric Wind",
    slug: "electric-wind",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/electricwind",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-electric-wind/public",
    tier: "value",
    discipline: ["reining","ranch"],
    stud_fee: 1000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Colonels Smoking Gun son · Reining and ranch · $1,000 fee 2026",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Colonels Smoking Gun","Grays Starlight","Smart Chic Olena"],
    traits: ["speed","athleticism","versatility","stop"],
    sire: "Colonels Smoking Gun",
    dam: "Grays Starlight mare",
    description: "Colonels Smoking Gun son with Grays Starlight athleticism. Electric Wind is a versatile producer for reining and ranch horse programs at $1,000 for 2026.",
    breeding_note: "Million Dollar Challenge season price. Booking fee $500, balance on confirmed pregnancy."
  },
  {
    name: "Pale Face Dunnit",
    slug: "pale-face-dunnit",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/pale-face-dunnit",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-pale-face-dunnit/public",
    tier: "value",
    discipline: ["reining","ranch"],
    stud_fee: 2000,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Reduced fee 2026 · Hollywood Dun It son",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Hollywood Dun It","Smart Chic Olena","Colonel Freckles"],
    traits: ["athleticism","versatility","softness","stop","handle"],
    sire: "Hollywood Dun It",
    dam: "Smart Chic Olena mare",
    description: "Hollywood Dun It son out of a Smart Chic Olena mare. Pale Face Dunnit fee has been reduced from $3,750 to $2,000 for all of 2026. A versatile producer for reining and ranch horse programs with proven Hollywood Dun It athleticism.",
    breeding_note: "Reduced to $2,000 for all of 2026."
  },
  {
    name: "Catatomic",
    slug: "catatomic",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/catatomic-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-catatomic/public",
    tier: "value",
    discipline: ["reining","reined cow horse"],
    stud_fee: 300,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Junior stallion · High Brow Cat / Gunner cross",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["High Brow Cat","Colonels Smoking Gun","Smart Chic Olena"],
    traits: ["cow sense","athleticism","quick feet","stop"],
    sire: "Colonels Smoking Gun",
    dam: "High Brow Cat mare",
    description: "High Brow Cat cutting bloodlines crossed into Colonels Smoking Gun reining. Catatomic is a junior stallion combining natural cow sense with reining athleticism — an emerging cross for breeders seeking cattle instinct and performance ability at a $1,500 entry fee.",
    breeding_note: "Million Dollar Challenge season price. Purchase a breeding and receive a second breeding to any Silver Spurs junior stallion for $200."
  },
  {
    name: "My Customized Whiz",
    slug: "my-customized-whiz",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/mycustomizedwhiz",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-my-customized-whiz/public",
    tier: "value",
    discipline: ["reining"],
    stud_fee: 300,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Junior stallion · Topsail Whiz / Gunner / Smart Chic Olena",
    enrollments: ["NRHA Sire & Dam"],
    bloodlines: ["Topsail Whiz","Smart Chic Olena","Colonels Smoking Gun"],
    traits: ["stop","speed","power","athleticism","scope"],
    sire: "Topsail Whiz",
    dam: "Smart Chic Olena / Gunner mare",
    description: "Junior stallion combining three elite reining sire lines: Topsail Whiz, Smart Chic Olena, and Colonels Smoking Gun. My Customized Whiz represents an outstanding bloodline combination at junior stallion pricing — ideal for breeders seeking proven reining genetics at $1,500.",
    breeding_note: "Million Dollar Challenge season price. Purchase a breeding and receive a second breeding to any Silver Spurs junior stallion for $200."
  },
  {
    name: "Docs Soula",
    slug: "docs-soula",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/docs-soula-1",
    photo: "https://imagedelivery.net/9VlM7Y9GaQMXOu5Ypg50yA/stallion-docs-soula/public",
    tier: "value",
    discipline: ["reined cow horse","cutting"],
    stud_fee: 300,
    lifetime_earnings: 0,
    offspring_earnings: 0,
    performance_summary: "Junior stallion · Doc Bar / Smart Chic Olena · Cow horse and cutting",
    enrollments: ["NRCHA Sire & Dam"],
    bloodlines: ["Doc Bar","Smart Chic Olena","Colonel Freckles"],
    traits: ["cow sense","athleticism","rate","turn","quick feet"],
    sire: "Doc Bar",
    dam: "Smart Chic Olena mare",
    description: "Junior stallion with deep cow horse and cutting lineage. Doc Bar foundation crossed with Smart Chic Olena handle produces horses with natural cattle instinct and quick feet. Docs Soula is enrolled in the NRCHA Sire and Dam program at $1,500.",
    breeding_note: "Million Dollar Challenge season price. Purchase a breeding and receive a second breeding to any Silver Spurs junior stallion for $200."
  },
  {
    name: "Boemil Twin Robotop",
    slug: "boemil-twin-robotop",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/boemil-twin-robotop",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 1500,
    lifetime_earnings: 37489,
    offspring_earnings: 0,
    performance_summary: "NRHA world's top money-earning Appaloosa · 2015 NRHA Open Class Futurity Champion · 2014 FEI World Equestrian Games, Team Italy",
    enrollments: [],
    bloodlines: ["Topsail Speckles", "Boemil Valentwin"],
    traits: [],
    sire: "Topsail Speckles",
    dam: "Boemil Valentwin",
    description: "2006 Appaloosa stallion and the NRHA's top money-earning Appaloosa with $37,489 in lifetime earnings. 2015 NRHA Open Class Futurity Champion, with a European record including the 2014 FEI World Equestrian Games as part of Team Italy and multiple Italian NRHA Derby titles.",
    breeding_note: "Frozen semen only. 2026 breeding fee includes a $500 booking fee.",
    profile: false
  },
  {
    name: "Boom Shernic",
    slug: "boom-shernic",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/boom-shernic",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 500,
    lifetime_earnings: 278303,
    offspring_earnings: 583000,
    performance_summary: "LTE $278,303 · Offspring earnings $583,000+",
    enrollments: [],
    bloodlines: ["Boomernic", "She And Chic Dunit"],
    traits: [],
    sire: "Boomernic",
    dam: "She And Chic Dunit",
    description: "2004 AQHA sorrel stallion by Boomernic out of She And Chic Dunit, with lifetime earnings of $278,303 and offspring earnings over $583,000. Silver Spurs presents him as a non-pro's stallion. 5-panel N/N, IMM N/N, 14.3 hands.",
    breeding_note: "Standing at Silver Spurs Equine, Scottsdale AZ. Million Dollar Challenge season price, reduced from $1,000. Booking fee $200, balance due on confirmed pregnancy.",
    profile: false
  },
  {
    name: "Cromed Out Mercedes",
    slug: "cromed-out-mercedes",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/cromed-out-mercedes-1",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 750,
    lifetime_earnings: 146650,
    offspring_earnings: 1345000,
    performance_summary: "NRHA Million Dollar Sire · 2009 NRBC Open Classic Champion · LTE $146,650+",
    enrollments: [],
    bloodlines: ["Custom Crome", "Princess In Diamonds"],
    traits: [],
    sire: "Custom Crome",
    dam: "Princess In Diamonds",
    description: "2005 AQHA bay stallion by Custom Crome out of Princess In Diamonds. NRHA Million Dollar Sire with offspring earnings over $1,345,000 and lifetime earnings of $146,650+. 2009 NRBC Open Classic Champion. 5-panel N/N, IMM N/N, 14.3 hands.",
    breeding_note: "ICSI breeding only. Standing at Silver Spurs Equine, Scottsdale AZ. Million Dollar Challenge season price, reduced from $1,500. Booking fee $250, balance due on a foal on the ground.",
  },
  {
    name: "Da Care Bear",
    slug: "da-care-bear",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/dacarebear",
    tier: "value",
    discipline: ["team roping"],
    stud_fee: 300,
    lifetime_earnings: 6200,
    offspring_earnings: 0,
    performance_summary: "AQHA Superior Heading Horse · 91.5 AQHA performance points in heading and heeling",
    enrollments: [],
    bloodlines: ["Boomernic", "Ms Boon Boom Command", "Docs Fritzie Command"],
    traits: [],
    sire: "Boomernic",
    dam: "Ms Boon Boom Command by Docs Fritzie Command",
    description: "2007 AQHA bay stallion by NRHA Hall of Fame sire Boomernic, out of Ms Boon Boom Command. Campaigned as a rope horse, earning over $6,200 and 91.5 AQHA points in heading and heeling, and awarded the AQHA Superior Heading Horse title. 5-panel N/N, IMM N/N, 15 hands.",
    breeding_note: "Million Dollar Challenge season price. Purchase a breeding and receive a second breeding to any Silver Spurs junior stallion for $200.",
    profile: false
  },
  {
    name: "Epic Titan",
    slug: "epic-titan",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/epic-titan",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2500,
    lifetime_earnings: 82200,
    offspring_earnings: 315000,
    performance_summary: "Cactus Classic Champion · NRBC Derby Reserve Champion · Reining By The Bay Reserve Champion · LTE $82,200+",
    enrollments: [],
    bloodlines: ["Colonels Smoking Gun", "Princess In Diamonds"],
    traits: [],
    sire: "Colonels Smoking Gun",
    dam: "Princess In Diamonds",
    description: "2013 AQHA/APHA sorrel stallion by Colonels Smoking Gun (Gunner) out of Princess In Diamonds. Cactus Classic Champion, NRBC Derby Reserve Champion, and Reining By The Bay Reserve Champion, with lifetime earnings of $82,200+ and offspring earnings over $315,000. 5-panel N/N, IMM N/N, 14.3 hands.",
    breeding_note: "Standing at Silver Spurs Equine. Million Dollar Challenge season price. Booking fee $750, balance due on confirmed pregnancy.",
    profile: false
  },
  {
    name: "Haboomamatada",
    slug: "haboomamatada",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/haboomamatada",
    tier: "value",
    discipline: ["reining", "reined cow horse", "cutting"],
    stud_fee: 300,
    lifetime_earnings: 0,
    offspring_earnings: 960,
    performance_summary: "2007 Scottsdale Classic Open Futurity 3rd · Offspring earnings across roping, barrel, and pole bending",
    enrollments: [],
    bloodlines: ["Boomernic", "Fives Little Lena", "Smart Little Lena"],
    traits: [],
    sire: "Boomernic",
    dam: "Fives Little Lena by Smart Little Lena",
    description: "2004 stallion by Boomernic out of Fives Little Lena, a daughter of Smart Little Lena. Third in the 2007 Scottsdale Classic Open Futurity. Silver Spurs positions him as a crossover option for reining or working cow and cutting programs. 5-panel N/N, IMM N/N, 14.2 hands.",
    breeding_note: "Million Dollar Challenge season price. Purchase a breeding and receive a second breeding to any Silver Spurs junior stallion for $200.",
    profile: false
  },
  {
    name: "Im A Fancy PYC",
    slug: "im-a-fancy-pyc",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/im-a-fancy-pyc",
    tier: "mid",
    discipline: ["racing"],
    stud_fee: 2500,
    lifetime_earnings: 454765,
    offspring_earnings: 4203000,
    performance_summary: "AQHA racing sire · SI 92 · 5 wins, $454,765 · 1st Remington Park Oklahoma Bred Futurity (G3) · Offspring earnings $4,203,000+",
    enrollments: ["Black Gold Incentive", "Oklahoma Bred Incentive"],
    bloodlines: ["PYC Paint Your Wagon", "First Prize Fancy"],
    traits: [],
    sire: "PYC Paint Your Wagon",
    dam: "First Prize Fancy",
    description: "2012 brown stallion by PYC Paint Your Wagon out of First Prize Fancy, speed index 92. Won the Remington Park Oklahoma Bred Futurity (G3) among 5 wins and $454,765 of his own, and ranked as the third highest producing second-year sire in 2019. Offspring earnings exceed $4,203,000. 5-panel N/N, 16.3 hands.",
    breeding_note: "On-farm breeding only. Standing at Silver Spurs Equine, Purcell OK. Fee includes the booking fee.",
    profile: false
  },
  {
    name: "Ruf Lil Magnum",
    slug: "ruf-lil-magnum",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/ruf-lil-magnum",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 2000,
    lifetime_earnings: 123000,
    offspring_earnings: 357000,
    performance_summary: "AQHA World Champion Senior Reining · LTE $123,000+ · Offspring earnings $357,000+",
    enrollments: [],
    bloodlines: ["Magnum Chic Dream", "Dun It A Lil Ruf"],
    traits: [],
    sire: "Magnum Chic Dream",
    dam: "Dun It A Lil Ruf",
    description: "2012 AQHA sorrel stallion known as “The Rock,” by Magnum Chic Dream out of Dun It A Lil Ruf. AQHA World Champion in Senior Reining with lifetime earnings of $123,000+ and offspring earnings over $357,000. 5-panel N/N, IMM N/N, 14.1 hands.",
    breeding_note: "Standing at Silver Spurs Equine, Scottsdale AZ. Booking fee $750, balance due on confirmed pregnancy.",
    profile: false
  },
  {
    name: "What It Takes",
    slug: "what-it-takes",
    station: "Silver Spurs Equine",
    source_url: "https://www.silverspursequine.com/what-it-takes",
    tier: "mid",
    discipline: ["reining"],
    stud_fee: 1000,
    lifetime_earnings: 0,
    offspring_earnings: 116000,
    performance_summary: "2009 & 2007 US National Arabian Reining Horse Champion \u00b7 2007 & 2006 Scottsdale Arabian Show Reining Champion \u00b7 2006 Youth National Championship Reining Champion \u00b7 AQHA offspring earnings $116,000+",
    enrollments: [],
    bloodlines: ["Ga N Khredible", "Sonoma Sensation", "Khemosabi"],
    traits: [],
    sire: "Ga N Khredible",
    dam: "Sonoma Sensation",
    description: "2001 Arabian reining stallion by Ga N Khredible out of Sonoma Sensation, tracing to Khemosabi. Multiple US National Arabian Reining Horse Champion, in 2009 and 2007, with Scottsdale Arabian Show and Region 7 championships and a 2005 Arabian Horse Futurity title. Silver Spurs credits him as sire of several top-five purebred and Half-Arabian reining champions, with AQHA offspring earnings over $116,000.",
    breeding_note: "Standing at Silver Spurs Equine, Scottsdale AZ. Fee reduced to $1,000. Booking fee $519.",
    profile: false
  }
];
